spring:
  profiles:
    active: dev
  application:
    name: identity-service
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://127.0.0.1:9999

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

