client-security-matchers: >
  /bookmark/**,
  /history/**,
  /ces/**,
  /forums/**,
  /login/**,
  /oauth2/**,
  /logout/**,
  /en/**,
  /auth/**,
  /business/**,
  /profile/**,
  /contents/**,
  /users/**,
  /media/**,
  /notifications/**,
  /community/**,
  /identity/**

client-permit-matchers: >
  /ces/**,
  /forum/**,
  /users/**",
  /contents/**,
  /users/**,
  /media/**,
  /forums/**,
  /notifications/**,
  /community/**
  /users/**,
  /login/**,
  /oauth2/**,
  /en/**,
  /auth/**,
  /contactSupport/**,
  /error/**,
  /actuator/**,
  /info/**,
  /health/**,
  /prometheus/**,
  /business/**,
  /profile/**,
  /identity/**

spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://127.0.0.1:9999

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE

server:
  port: 8168

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    gateway:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: always